Repository platform9/pf9-ui-plugin, pull requests merged in 2019-10, with the labels that each got.

#396 Misc fixes to Monitoring page
  package-lock.json
  src/api-client/Qbert.js
  src/app/plugins/kubernetes/components/prometheus/actions.js
Labels: bug

#405 Fix metrics port label
  src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
Labels: bug

#408 [WIP] Reload storageClass list after adding
  src/api-client/Qbert.js
  src/app/plugins/kubernetes/components/common/ClusterPicklist.js
  src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
  src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
  src/app/plugins/kubernetes/components/storage/StorageClassesPage.js
  src/app/plugins/kubernetes/components/storage/actions.js
  src/app/plugins/kubernetes/index.js
Labels: WIP

#410 Fix prometheus rules page
  src/api-client/Qbert.js
  src/app/plugins/kubernetes/components/prometheus/PrometheusRules.js
  src/app/plugins/kubernetes/components/prometheus/PrometheusRulesTable.js
  src/app/plugins/kubernetes/components/prometheus/actions.js
Labels: bug

#416 Add grafana dashboard link
  src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
  src/app/plugins/kubernetes/components/infrastructure/clusters/DashboardLink.js
  src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
Labels: enhancement
